### ISSUE TITLE
How to create sms gateway for drupal

### ISSUE THREAD

**Issue by ugintl** [arthurbuliva/smssync#1]
I have found some open source gateways which I would like to use with drupal as sms gateways and alternative to twilio etc. I would use it sms framework module.

Can you guide me how I can do it?

Here you will find open source sms gateways. https://socialcompare.com/en/comparison/sms-gateways-1odvv6xv

**Comment by arthurbuliva** [comment]
This module is old and I unfortunately haven't had the time to maintain nor upgrade it. Please use it knowing that there may be bugs that won't be fixed.
