### ISSUE TITLE
Will it work with sms framework module?

### ISSUE THREAD

**Issue by ugintl** [arthurbuliva/smssync#2]
Will this module work with sms_framework?

**Comment by arthurbuliva** [comment]
I don’t know what you mean by sms_framework. In any case this module is based on sms_sync. I haven’t had time to update it thus I don’t know if it still works. Unfortunately, therefore, I can’t offer much support other than what’s already written in the description of the module

**Comment by ugintl** [comment]
sms_framework is a drupal module. Anyway thanks
